### ISSUE TITLE
Hello World script not printing to task console

### ISSUE THREAD

**Issue by jgreer0417** [osirixgrpc/osirixgrpc#19]
### Contact Details

jgreer0417@gmail.com

### Documentation Scope

OsiriXgrpc

### OsiriXgrpc Version

0.2.1-beta0

### What would you like to see?

Hi,
I am copying my comment from the discussion section below, as requested:

I am struggling to get a python test script working, and wanted to ask if I might be missing something obvious.

I have a simple hello world script installed that shows up under the gRPC tasks menu, but I cannot tell if it is running. 
It is a .py script that only contains print("hello world"), and nothing appears in the "Task Console" window.

Do you expect this script to work as described? Or do some Osirix packages need to be imported?

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdblackledge** [comment]
Would you mind sharing a copy of your script so I can take a look at it?

**Comment by jgreer0417** [comment]
[main.py.zip](https://github.com/user-attachments/files/16631934/main.py.zip)
 zipped to allow upload. It really is as simple as described.

**Comment by mdblackledge** [comment]
Many thanks! I wonder if this is to do with the interpreter you are using.  If you go to "Script Management" in the Plugins/Database/osirixgrpc menu item, is the "Interpreter" set to /user/bin/python?  If so this is probably incorrect and you should change to a different interpreter. This can vary depending on your setup. I do this by installing [miniconda](https://docs.anaconda.com/miniconda/) on my system, and then in the management table click on the arrow <img width="23" alt="arrow" src="https://github.com/user-attachments/assets/01f76fda-0524-4cc1-9f2a-d242f303d28c"> on the row relevant to your plugin and point it to the relevant interpreter.  For example, mine points to: `/Users/mblackledge/miniforge3/bin/python`.  Otherwise, this works fine on my side.  Thanks for your feedback and do let me know how it goes.

**Comment by jgreer0417** [comment]
That was it. Thank you!

**Comment by mdblackledge** [comment]
Perfect.  Thanks for letting us know and do comment again if there's anything else we can do to help!
